"""unique room names.

Revision ID: 53288d545c7d
Revises: 362d56f85cde
Create Date: 2020-12-16 16:20:03.129368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53288d545c7d'
down_revision = '362d56f85cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_name')
        batch_op.create_index(batch_op.f('ix_rooms_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_name'))
        batch_op.create_index('ix_rooms_name', ['name'], unique=False)

    # ### end Alembic commands ###
