"""Init db 🎈

Revision ID: 6eb2ce49d533
Revises: 
Create Date: 2021-07-26 21:37:08.633859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb2ce49d533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('need', 'feeling', name='type'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_type'), ['type'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_name'), ['name'], unique=True)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('NEED_MET', 'NEED_NOT_MET', 'DEFINE', 'THINK', name='type'), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_type'))
        batch_op.drop_index(batch_op.f('ix_comments_id'))
        batch_op.drop_index(batch_op.f('ix_comments_data'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))

    op.drop_table('comments')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_name'))
        batch_op.drop_index(batch_op.f('ix_rooms_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_created_at'))

    op.drop_table('rooms')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_type'))
        batch_op.drop_index(batch_op.f('ix_cards_name'))
        batch_op.drop_index(batch_op.f('ix_cards_level'))
        batch_op.drop_index(batch_op.f('ix_cards_id'))

    op.drop_table('cards')
    # ### end Alembic commands ###
