"""Add stories, scenes and guesses.

Revision ID: eb05cb41480c
Revises: cde071912d0a
Create Date: 2022-03-21 20:30:46.943074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb05cb41480c'
down_revision = 'cde071912d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_id'), ['id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('noun', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_position'), ['position'], unique=False)

    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guesses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guesses_id'), ['id'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index('ix_rooms_created_at')
        batch_op.drop_index('ix_rooms_id')
        batch_op.drop_index('ix_rooms_name')

    op.drop_table('rooms')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('definition_source',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('definition_source',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index('ix_rooms_name', ['name'], unique=False)
        batch_op.create_index('ix_rooms_id', ['id'], unique=False)
        batch_op.create_index('ix_rooms_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guesses_id'))
        batch_op.drop_index(batch_op.f('ix_guesses_created_at'))

    op.drop_table('guesses')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_position'))
        batch_op.drop_index(batch_op.f('ix_scenes_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_id'))

    op.drop_table('stories')
    # ### end Alembic commands ###
